### ISSUE TITLE
Native packages for Alpine

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#16]
Create a workflow to generate alpine packages of the prover, triggered by a git tag based on commits in the [stone-prover](https://github.com/baking-bad/stone-prover) repository.
https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/release.yml and https://github.com/dipdup-io/stone-packaging/blob/master/package_deb.sh can be used as examples.

- Testing should be done in a forked repo and testing results should be provided.
- [README](https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#download-native-packages-for-debianubuntu) should be extended with instructions similar to.

**Comment by CollinsC1O** [comment]
Hi @dmirgaleev I'm a frontend developer and also a blockchain developer. I'm ready to work, please assign

**Comment by Botdavid** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a full stark  web developer, graphics designer and a content  writer

### How I plan on tackling this issue
Using the guidelines provided, i will duly implement all the instructions to generate a perfect workflow

**Comment by MrRoudyk** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Software Engineer with 10 years of experience. For the past 5 years, I’ve specialized in HR Tech solution, now utilized by tens of thousands of companies and hundreds of thousands of users.
Key Skills: Software Development, UI/UX, Systems Design, Python, 1C:Enterprise, SQL, JavaScript, React.js.
I’m passionate about exploring new technologies and currently looking to deepen my expertise in GitHub Actions, Bash scripting, and package management.

### How I plan on tackling this issue
I will follow the recommendations and instructions, as well as apply the experience from the files located at https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/release.yml and https://github.com/dipdup-io/stone-packaging/blob/master/package_deb.sh

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
Fork the repository for testing:

    Fork the stone-prover repository.
    Clone it locally for testing.

Define the GitHub Actions Workflow:

    Add a new workflow in .github/workflows/release-alpine.yml.
    This workflow will be triggered by Git tags and will handle the generation of Alpine packages.

Modify and Add Build Scripts:

    Create a package_alpine.sh script similar to package_deb.sh, but adjust it for Alpine Linux package creation.
    Ensure that it uses the Alpine package manager (apk) and Alpine-specific build tools like abuild or apkbuild.

Create the Workflow File (release-alpine.yml)

Create the Alpine Packaging Script (package_alpine.sh)

Test in the Forked Repository:

    Push the changes to your forked repository.
    Tag a commit to trigger the GitHub Actions workflow.
    Check the results of the workflow to ensure it successfully builds and uploads the Alpine package.

Update the README with Instructions:

    After successful testing, update the README with instructions similar to other examples, explaining how to trigger the workflow and download the Alpine package.

    Submit Test Results:
        After testing, provide screenshots or logs showing the successful execution of the workflow in your forked repository.

**Comment by dmirgaleev** [comment]
Hi @devcollinss! Welcome aboard! Please don't hesitate to join our Telegram group [t.me/baking_bad_odhack](https://t.me/baking_bad_odhack) to ask questions and share your progress! Happy hacking!

**Comment by dmirgaleev** [comment]
Friendly heads up that you have till Sunday (October 6) to push final PR. @devcollinss
