### ISSUE TITLE
Native packages for Homebrew

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#17]
Create a workflow to generate homebrew packages of the prover, triggered by a git tag based on commits in the [stone-prover](https://github.com/baking-bad/stone-prover) repository. 
https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/release.yml and https://github.com/dipdup-io/stone-packaging/blob/master/package_deb.sh can be used as examples.

- Testing should be done in a forked repo and testing results should be provided.
- [README ](https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#download-native-packages-for-debianubuntu)should be extended with instructions similar to .

**Comment by supreme2580** [comment]
@dmirgaleev Hi can I be assigned to this?

**Comment by CollinsC1O** [comment]
Hi @dmirgaleev I will love to work on this

**Comment by Botdavid** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a full stark  web developer, graphics designer and a content  writer

### How I plan on tackling this issue
Using the guidelines provided, i will duly implement all the instructions to generate a perfect workflow

**Comment by ayush-ranjan-official** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a Blockchain Developer, specializing in EVM based chains, I also have some experiences in software development role. I just completed Starknet's Basecamp and Buidl Camp, which introduced me to Cairo and starknet Ecosystem. Now, I want to start contributing to this ecosystem and stone-packaging seems to be the best place to start considering my recent interest in zero-knowledge proofs based projects.

### How I plan on tackling this issue
Step 1: To trigger by a git tag based on commits i'll use the following syntax -
```
on:
  push:
    tags:
      - 'v*.*.*'
```
Step 2: Looking at the examples provided, I'll keep the similar code for releasing the project keeping in mind the docker installation steps for Stone-prover project- 
```
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]

    steps:
     ... 
```
Step 3: I will add steps to Generate Homebrew Formula, using a code similar to the example below -
```
class Foo < Formula
  desc ""
  homepage ""
  url "https://example.com/foo-0.1.tar.gz"
  sha256 "85cc828a96735bdafcf29eb6291ca91bac846579bcef7308536e0c875d6c81d7"
  license ""

  # depends_on "cmake" => :build

  def install
    # ENV.deparallelize
    system "./configure", *std_configure_args, "--disable-silent-rules"
    # system "cmake", "-S", ".", "-B", "build", *std_cmake_args
    system "make", "install"
  end

  test do
    system "false"
  end
end
```
step 4 : Upload and Submit Homebrew formula.

**Comment by MrRoudyk** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Software Engineer with 10 years of experience. For the past 5 years, I’ve specialized in HR Tech solution, now utilized by tens of thousands of companies and hundreds of thousands of users.
Key Skills: Software Development, UI/UX, Systems Design, Python, 1C:Enterprise, SQL, JavaScript, React.js.
I’m passionate about exploring new technologies and currently looking to deepen my expertise in GitHub Actions, Bash scripting, and package management.

### How I plan on tackling this issue
I will follow the recommendations and instructions, as well as apply the experience from the files located at https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/release.yml and https://github.com/dipdup-io/stone-packaging/blob/master/package_deb.sh

**Comment by dmirgaleev** [comment]
Hi @MrRoudyk! Welcome aboard! Please don't hesitate to join our Telegram group [t.me/baking_bad_odhack](https://t.me/baking_bad_odhack) to ask questions and share your progress! Happy hacking!

**Comment by dmirgaleev** [comment]
Friendly heads up that you have till Sunday (October 6) to push final PR. @MrRoudyk

**Comment by MrRoudyk** [comment]
Thank you for the heads up. I’m reviewing the task and will propose a solution within the next couple of days. @dmirgaleev
