### ISSUE TITLE
GitHub Action for DockerHub build and publish

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#19]
Create a GitHub Actions workflow to publish docker images to Docker Hub. https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/ghcr.yml can be used as an example. 

- Testing should be done in a forked repo and testing results should be provided.
- [README](https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#download-minimal-docker-images-for-x86_64) should be updated. 
- For authorization should be used           
 ```
username: ${{ secrets.DOCKER_LOGIN }}
password: ${{ secrets.DOCKERHUB_TOKEN }}
 ```

**Comment by Gift-Naomi** [comment]
@dmirgaleev Can I work on this issue?

**Comment by martinvibes** [comment]
hello @dmirgaleev please can i be assigned to this issue?

i have done something like this before on an issue i was assigned
i will be able to tackle this issue if i am assigned

**Comment by vickiddev** [comment]
hello @dmirgaleev can i work on this issue

**Comment by ShantelPeters** [comment]
@dmirgaleev can i please work on this issue ?

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Would follow the specifications given in this article by github https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
i am a frontend developer with experience in using git version control , linux cli, frontend end technologies. with these experience of mine i know i would be able to handle the following task. kindly assign me

### How I plan on tackling this issue
I will begin by forking the original repository where the GitHub Actions workflow needs to be implemented. This will allow me to test changes without affecting the main project.

Create GitHub Actions Workflow:
I will navigate to the .github/workflows directory in my forked repository and create a new YAML file (e.g., docker-publish.yml).
I will refer to the example provided at the link (https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/ghcr.yml) to understand how to structure the workflow for publishing Docker images to Docker Hub.
Define Workflow Triggers:

In the workflow file, I will specify triggers such as push or pull_request to determine when the workflow should run.
Configure Docker Login Step:

I will add a step in the workflow to log in to Docker Hub using the provided

Build Docker Image:

I will add a step to build the Docker image, specifying the necessary context and Dockerfile path.
Publish Docker Image:

I will include a step to push the built image to Docker Hub, ensuring the image tag is appropriately set.
Test the Workflow:

After setting up the workflow, I will commit my changes and push them to the forked repository. I will then monitor the Actions tab on GitHub to check if the workflow runs successfully.
Provide Testing Results:

I will document the results of the workflow run, including any success or failure messages, and address any issues that arise during testing.
Update README:

Finally, I will update the README file of the repository to include instructions on how to use the new GitHub Actions workflow for publishing Docker images, providing clear guidance for future contributors.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I have a background in software development with experience in frontend technologies like JavaScript and React, as well as backend skills in Python and Flask

### How I plan on tackling this issue
Locate Config File: Find the relevant Hasura configuration file (hasura.yaml or config.yaml).

Modify Config: Add a section in the configuration file to include:

```
hasura:
  url: <your_hasura_endpoint>
  ignore_internal: true
  ignore:
    - some_user_table
```
Implement Logic: Ensure backend logic skips tables that match the ignore_internal setting, filtering out those starting with dipdup_ or specified in the ignore list.

Test Configuration: Run Hasura migrations to confirm that the specified internal tables are excluded from the GraphQL API while ensuring other tables function correctly.

Update Documentation: Document the new configuration options for other developers.

Version Control: Commit the changes with clear messages about the new functionality.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding.I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. In .github/workflows/ directory, create a new workflow file named docker-publish.yml or modify the existing ghcr.yml in order to use Docker Hub instead of GitHub Container Registry.
2. Testing in a forked repo, check actions tab in my github repository to monitor the workflow execution and verify the logs to ensure that the docker image is built and published successfully to docker hub
3. Update README to include information about the new workflow.

**Comment by jsanchez556** [comment]
@dmirgaleev thanks for the opportunity.

**Comment by dmirgaleev** [comment]
Hello @jsanchez556! Welcome aboard! The branch name completely up to you. Let's use informative commit messages. Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!
