### ISSUE TITLE
[Book] Integrate Vocs framework  

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#21]
Integrate vocs framework https://vocs.dev/docs to assemble a static site out of markdown files.  
Add instructions how to build and run dev server locally to the readme (+ installation steps).

References:
- https://github.com/dojoengine/book

**Comment by CollinsC1O** [comment]
Hi @dmirgaleev I'm a frontend and a blockchain developer. I will love to work on this. I'm ready to work

**Comment by ShantelPeters** [comment]
i will like to work on this issue @dmirgaleev kindly assign i am ready to work.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
 i am a frontend developer with experience in technical writing and documentation using tools like Docusaurus and Jekyll. with my experience using the framework i would be able to handle this task as vocs is also a similar framework

### How I plan on tackling this issue
 1. Set up the project with VOCS
 2. Organize markdown file by placing them in a directory and configuring Vocs to pull content from this directory.
 3. Configure the VOCS to build the static site using the files in 2 above
 4. set up the dev server
 5. Add all the building and run instruction to  the readme file.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a blockchain developer with vast experiences with in css ,react, typescript,javascript ,solidity etc.

### How I plan on tackling this issue
I intend to approach the problem with the following : 
1. Set Up Vocs: Follow the [Vocs documentation](https://vocs.dev/docs) to install the framework. Use the instructions to assemble the static site from the existing markdown files.   
2. Configure Build: Ensure the site is configured properly by adding necessary configurations (e.g., `vocs.config.js`).
3. Update README:
   - Include installation steps (e.g., `npm install vocs` or other dependencies).
   - Add instructions for building (`vocs build`) and running the dev server (`vocs dev`) locally.

4. Test: Verify the build and dev server locally to ensure everything runs smoothly.

I am using the [DojoEngine book repo](https://github.com/dojoengine/book) as a reference

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello, I am Joseph I am a Software developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/ I have also written articles too here is an article for written for Karst 

### How I plan on tackling this issue
The descriptionis already detailed I will follow it to solve the issue in 2-3 days

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
 i will Understand VOCs Framework
Study the VOCs framework:
Define VOCs and its importance
Identify key components (e.g., collect, analyze, act)
 Identify Customer Feedback Channels
Determine customer feedback channels:
Surveys
Social media
Support tickets
Reviews

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue

please kindly assign me and i'll get straight to work

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I have experience in web development and frontend frameworks, particularly with static site generation and Markdown integration.



### How I plan on tackling this issue
I would integrate the Vocs framework by setting it up to generate a static site from Markdown files, updating the README with build and run instructions, and testing the integration to ensure everything works smoothly.

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I hold a degree in computer science and have worked as a mobile developer with React and JavaScript, two of the Vocs framework's primary technologies. I have experience working with static site generators such as Jekyll and Docusaurus on a number of documentation projects. My knowledge of contemporary web technologies and my experience with frontend development make me a good fit to integrate Vocs and enhance the project's documentation system.


### How I plan on tackling this issue
Studying the Vocs documentation and the present project structure would be my first steps. Next, I would configure Vocs in the project such that it would function with the already-existing markdown files. I would make a vocs.config.js file to alter the look and feel of the website. I would then modify the build procedure to use Vocs to create the static website. For local testing, I would include a dev server script. Lastly, I would provide explicit instructions to the README for installing the software, creating the website, and starting the development server locally. I would make sure the current material is correctly transferred and rendered in the new system during the entire process.

**Comment by dmirgaleev** [comment]
Hello @akintewe! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress! It is recommended to share your progress on a daily basis.  Happy hacking!

**Comment by akintewe** [comment]
Thank you very much for this opportunity

**Comment by dmirgaleev** [comment]
Resolved in https://github.com/dipdup-io/stone-packaging/pull/44
