### ISSUE TITLE
[Book] Install Stone from sources

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#22]
Write a documentation page describing how to build Stone prover/verifier from sources.
Add instruction how to locate the built binaries.

Note that MacOS/ARM enabled fork is https://github.com/baking-bad/stone-prover
Some hints for the documentation can be taken from https://github.com/dipdup-io/stone-packaging/blob/master/build.sh or https://github.com/dipdup-io/stone-packaging/blob/master/Dockerfile

Path to your markdown file: `docs/pages/install/sources.md`

**Comment by od-hunter** [comment]
Hi @dmirgaleev , can I be assigned this when od hack starts please?

**Comment by vickiddev** [comment]
hello @dmirgaleev i am a frontend developer and a technical writer 
please can i work on this issue when the OD hack starts please :)
i would love to be a contributor on this repo

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a blockchain developer and a technical writer 
please can i work on this issue :) and would love to be a contributor

**Comment by Joy-Adah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
My name is Joy and I am a web3 developer and contributor. I also have experience in writing documentations. 

### How I plan on tackling this issue
I plan to approach this problem by writing a detailed documentation on how to build the Stone prover and verifier from different sources. I will also ensure that the documentation includes how to locate the built binaries.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I  am a blockchain developer ,this would be my first time contributing to this ecosystem.

### How I plan on tackling this issue

1 Gather Information: Collect all necessary steps for building the Stone prover/verifier from the source, focusing on the MacOS/ARM fork available at [baking-bad/stone-prover](https://github.com/baking-bad/stone-prover).

2. **Write Documentation**:
   - Introduction: Briefly describe what Stone prover/verifier is and its purpose.
 
3. Markdown Formatting: Format ontent in Markdown style for clarity and ease of reading. Use headers, code blocks, and lists for better organization.
4. Review and Test: Ensure the instructions are accurate by testing them on a MacOS/ARM system, if possible, and revise based on any issues encountered.
5. Add to Documentation: Save the file as `docs/pages/install/sources.md` and integrate it into the overall documentation structure.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo



### How I plan on tackling this issue
Review Build Instructions: Check the GitHub link for the MacOS/ARM fork for specific build details.
Gather Information: Research the necessary dependencies and tools for building Stone.
Outline Structure: Plan the markdown file’s content, including an introduction, prerequisites, step-by-step build instructions, and how to locate the built binaries.
Write Documentation: Create the markdown file at docs/pages/install/sources.md using clear language.
Review and Edit: Ensure clarity, accuracy, and consistent formatting.
Commit Changes: Save the markdown file with a clear commit message.
Seek Feedback: Optionally, request peer feedback to improve the documentation.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello , I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is an article I wrote for Karst https://medium.com/@josephchimebuka/krast-a-decentralized-social-graph-built-on-starknet-with-erc-6551-c4c9800b5a9d

### How I plan on tackling this issue
I will write a documentation page describing how to build Stone prover/verifier from sources. and add instruction how to locate the built binaries.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I’m Benjamin, and I’m willing to create a new documentation page that will guide users on how to build the Stone prover and verifier from the source code. With 18 contributions since joining OnlyDust, I’m experienced in writing documentation and ready to make this process clear for everyone.

### How I plan on tackling this issue
The main goal of this documentation is to help users easily understand how to compile the Stone prover and verifier from the source. I’ll provide step-by-step instructions, making sure that even those who are new to building software can follow along without any confusion.

I will also include information on how to locate the built binaries after the compilation process. This is essential because users will need to know where to find the final output once they’ve successfully built the software.

There’s a MacOS/ARM enabled fork available at baking-bad/stone-prover. This information will be crucial for Mac users who want to build the Stone prover on their systems.

The documentation will be written in a markdown file located at docs/pages/install/sources.md, making it easy for everyone to access.

To ensure that the instructions are accurate and helpful, I’ll refer to the relevant sources and follow best practices in documentation writing. After drafting the page, I will review it for clarity and completeness, and I’ll be open to feedback from you to make sure it meets the needs of the project.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue

i will Briefly introduce Stone prover/verifier and its purpose
Explain the scope of the documentation page
 Prerequisites
List required dependencies and tools:
Operating system (e.g., Linux, macOS)
Programming languages (e.g., C++, Java)
Build systems (e.g., CMake, Maven)
Libraries (e.g., gmp, zlib)
 Downloading Sources
Provide instructions on downloading the Stone source code:
Git repository URL
Version control system (e.g., Git, SVN)

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue

please kindly assign me and i'll get straight to work

**Comment by dmirgaleev** [comment]
Hello @Joy-Adah! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by Joy-Adah** [comment]
Hello @dmirgaleev thanks!

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i would love to take on this issue

### How I plan on tackling this issue
kindly assign :)

**Comment by dmirgaleev** [comment]
Hello @MullerTheScientist! Welcome aboard! Please don't hesitate to join our Telegram group [t.me/baking_bad_odhack](https://t.me/baking_bad_odhack) to ask questions and share your progress! Happy hacking!

**Comment by MullerTheScientist** [comment]
hello @dmirgaleev Thank you for assigning me this issue!

**Comment by dmirgaleev** [comment]
Friendly heads up that you have till Sunday (October 6) to push final PR. @MullerTheScientist
