### ISSUE TITLE
[Book] Install Stone binaries

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#23]
Write a documentation page describing how to download Stone binaries depending on your OS/architecture.  
Remove the overlapping instructions from the readme https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#usage-instructions

Add instruction how to add binaries to PATH or how to "install" them by placing to `/usr/bin` or alternative locations.

Path to your markdown file: `docs/pages/install/binaries.md`

**Comment by od-hunter** [comment]
Hi @dmirgaleev , please can I work on this when od hack starts please?

**Comment by raizo07** [comment]
Hey @dmirgaleev I'll like to work on this

**Comment by vickiddev** [comment]
hello @dmirgaleev i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a blockchain developer and a technical writer
please can i work on this issue :) and would love to be a contributor

**Comment by ShantelPeters** [comment]
Please i will like to work on this @dmirgaleev

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Please can I be assigned this issue

### How I plan on tackling this issue
I can do this

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hi please can I be assigned this issue? This would be my first time contributing to this repo and I'd love to be given the opportunity to contribute to this project. I am a blockchain developer and I have experience in html, css, react, JavaScript,TypeScript and solidity, python and Cairo.
Below are some of the documentations I've done that were merged:

dojoengine/book#308 (comment)

keep-starknet-strange/joyboy#143 (comment),

horuslabsio/Starknet-Scaffold#94 (comment).

Some of my documentations outside GitHub:

https://t.co/ZgK0ccPZpw,

https://t.co/GnBqVQPECz.


### How I plan on tackling this issue
To solve this issue, I’d take the following steps:
1.⁠ ⁠I’ll write a brief overview of the Stone binaries and their purpose.
2.⁠ ⁠⁠I’ll write instruction for downloading binaries for different operating systems (Windows, macOS, Linux) and architectures (x86, ARM, etc.) and also provide links to the respective binary downloads.
3.⁠ ⁠⁠I’ll write step-by-step instructions on how to add the downloaded binaries to the system PATH, and also alternatives for "installing" binaries by placing them in /usr/bin or other suitable directories.
4.⁠ ⁠⁠Lastly, I’ll write instructions for verifying that the binaries are correctly installed and accessible.

Please assign me.

**Comment by augustin-v** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am self taught in most things I do, and I started programming this year with Rust. I have experience with Japanese documentation for the Aptos blockchain.
As you can see I have yet to contribute to OnlyDust, I would be very grateful to be given a chance for my first contribution.

### How I plan on tackling this issue
I would first gather information for the download instructions of each OS. Int the binaries.md provide a brief instruction to Stone, followed by clear steps on how to download and install the binaries for each OS. Also, as in the issue, add instructions on adding binaries to the PATH or moving them to `/usr/bin` or alternative locations. Finally, modify the existing README to remove overlapping instructions.

If I have any trouble I would make sure to communicate it clearly.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a front-end and also a blockchain developer with experience in technical writing and documentation 

### How I plan on tackling this issue
- I will provide links and steps on how to download Stone binaries for each OS (Linux, macOS, Windows) and respective architecture.
- I will instruct users on how to place binaries in system paths
- I will include steps to add the binary folder to the system PATH

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged

I am an advanced computer science student with experience in Java and JavaScript, and a member of the DOJO Coding community. I have worked on projects using React and TypeScript, with knowledge in both front-end and back-end development. I have implemented various components in admin dashboards, enhancing user interaction and form functionality. I have also collaborated in creating new task types and integrating additional features in complex systems. My focus is to ensure that each implementation seamlessly integrates with the existing structure, maintaining clean and maintainable code.

### How I plan on tackling this issue
To solve this issue, I plan to:

Provide a brief description of the Stone binaries and their purpose.
Include download and installation instructions for Windows, macOS, and Linux, including how to add the binaries to the PATH or place them in directories like /usr/bin.
Verify the correct installation of the binaries.
Update the README to avoid duplicating information.

**Comment by dmirgaleev** [comment]
Hello @CollinsC1O! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by CollinsC1O** [comment]
@dmirgaleev thanks allot

**Comment by dmirgaleev** [comment]
Hey @CollinsC1O! Do you have any progress so far?

**Comment by CollinsC1O** [comment]
Hello @dmirgaleev yes I have made progress. With the pr I created, I have removed the redundant step in the documentation I created and effected the changes to the README.MD instructing users to ensure to download the binaries instead of cloning and notifying users that they still need to clone the rrpo to create and verify a test proof. Been waiting for your review to ensure I implemented the changes as you exactly as you demanded or to make further corrections

**Comment by dmirgaleev** [comment]
Thank you for you work!

**Comment by CollinsC1O** [comment]
Hello @dmirgaleev I'm grateful for the opportunity to have contributed. Thanks allot for your patience
