### ISSUE TITLE
[Book] Install Stone Docker images

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#24]
Add a documentation page describing how to get Stone Docker images.  
Note that there are currently three images https://github.com/orgs/dipdup-io/packages?repo_name=stone-packaging
two lightweight that contain only single binary (prover or verifier) and another one that combines both.

Path to your markdown file: `docs/pages/install/docker.md`

**Comment by vickiddev** [comment]
hello @dmirgaleev i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I'll love to work on this

### How I plan on tackling this issue
Can I be assigned this issue

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a blockchain developer / technical writer with over 3 years experience

### How I plan on tackling this issue

1.*Research Docker Images: Review the Stone Docker images available at the [DipDup packages repository](https://github.com/orgs/dipdup-io/packages?repo_name=stone-packaging) to understand their purposes and how to obtain them.

2. Write Documentation
   - Introduction: Provide a brief overview of Stone and the purpose of the Docker images.
   - Available Images: Describe the three available images:

3. Markdown Formatting: Structure the content using appropriate Markdown syntax for headers, lists, and code blocks to enhance readability.
4. Review and Test: If possible, test the commands and instructions to ensure they work as expected, adjusting any inaccuracies.
5. Add to Documentation: Save the documentation as `docs/pages/install/docker.md` and ensure it fits within the overall documentation structure.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo



### How I plan on tackling this issue
Review Existing Images: Check the GitHub link for available Stone Docker images.
Gather Instructions: Research the installation process and Docker prerequisites.
Outline Structure: Plan the markdown file’s content, including an introduction, image list, installation steps, usage examples, and troubleshooting.
Write Documentation: Create the markdown file at docs/pages/install/docker.md.
Review and Edit: Ensure clarity, accuracy, and consistent formatting.
Commit Changes: Save the markdown file with a clear commit message.
Seek Feedback: Optionally, request peer feedback to improve the documentation.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a doc i wrote for karst https://medium.com/@josephchimebuka/krast-a-decentralized-social-graph-built-on-starknet-with-erc-6551-c4c9800b5a9d

### How I plan on tackling this issue
I will add a documentation page describing how to get Stone Docker images before submitting a PR and i will cnclude in 2-3 days

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
i will Briefly introduce Stone and Docker
Explain the benefits of using Stone Docker images
Prerequisites
List required tools and dependencies:
Docker Engine
Docker Hub account (optional)
Obtain Stone Docker Images
Describe ways to obtain Stone Docker images:
Pull from Docker Hub
Build from Dockerfile
Use pre-built images from GitHub Packages

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue
please kindly assign me and i'll get straight to work

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged

I am an advanced computer science student with knowledge in Docker and technical documentation writing, and a member of the DOJO Coding community here in CR. Although I haven't worked on projects using Docker, I have experience in researching and creating detailed guides for various technological tools. My goal is to ensure that the documentation is accurate and easy to follow, contributing to a better understanding and use of the available tools.

### How I plan on tackling this issue
I plan to research the Stone Docker images in the DipDup repository and create clear documentation in docs/pages/install/docker.md. I will include an introduction to Stone, a description of the available images, prerequisites, and ways to obtain them (Docker Hub, Dockerfile, or GitHub Packages). I will provide detailed steps for installation and usage, and verify that the instructions are accurate. I will request feedback to improve the quality of the document.

**Comment by dmirgaleev** [comment]
Hello @josephchimebuka! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by josephchimebuka** [comment]
Thank you @dmirgaleev I've joined the Telegram group already!

**Comment by dmirgaleev** [comment]
Hey @josephchimebuka! Do you have any progress so far?

**Comment by dmirgaleev** [comment]
Thanks for your work!
