### ISSUE TITLE
[Book] Install Stone deb package

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#25]
Add documentation page describing how to install Stone from a deb package on Ubuntu/Debian.

Path to your markdown file: `docs/pages/install/debian.md`

**Comment by Gift-Naomi** [comment]
@dmirgaleev Can I work on this please?

**Comment by ooochoche** [comment]
@dmirgaleev I would love to work on this

**Comment by vickiddev** [comment]
hello @dmirgaleev i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo

**Comment by martinvibes** [comment]
hello @dmirgaleev please can i work on this issue :)

**Comment by ShantelPeters** [comment]
can i work on this please @dmirgaleev

**Comment by Jemiiah** [comment]
@dmirgaleev I would love to work on this issue when  ODHack starts I have worked on about 6 different documentation issue on different repositories this is my OD Hack portfolio with over 50 contributions https://app.onlydust.com/u/Jemiiah I have a very good track record on docs issues here are some of the repositories I have worked on:
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/106
https://github.com/dragan2234/worldcoin-scroll-bridge/pull/13
https://github.com/dragan2234/worldcoin-scroll-bridge/pull/11
https://github.com/NethermindEth/StarknetByExample/pull/200

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a web3 developer/ Technical writer


### How I plan on tackling this issue
1. **File Setup**: Create a new markdown file at `docs/pages/install/debian.md`. Begin with a brief introduction of Stone and its purpose.

2. **Installation Instructions**: Provide step-by-step commands for downloading the `.deb` package, installing it using `dpkg`, and handling any missing dependencies with `apt-get`.

3. **Verification**: Include a final section for verifying installation with a version check command, and note any common troubleshooting tips (e.g., fixing broken dependencies).

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Please can I be assigned this issue? This would be my first time contributing to this repo and I'd love to be given the opportunity to contribute to this project. I am a blockchain developer and I have experience in html, css, react, JavaScript,TypeScript and solidity, python and Cairo.

### How I plan on tackling this issue
To solve this issue and to write a well detailed documentation, I’d take the following steps:
 1. I’ll write a brief overview of the Stone prover/verifier and its purpose.
2.⁠ ⁠I’ll document the required tools and dependencies for building Stone on various platforms.
3.⁠ ⁠⁠I’ll write a detailed step-by-step instructions for cloning the repository, Instructions for setting up the environment and dependencies and also commands to build the Stone prover/verifier.
4.⁠ ⁠⁠I’ll also write guidelines on where to find the generated binaries after the build process.

Please assign me, I am ready to work.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is an article I wrote for Karst https://medium.com/@josephchimebuka/krast-a-decentralized-social-graph-built-on-starknet-with-erc-6551-c4c9800b5a9d

### How I plan on tackling this issue
I will add documentation page describing how to install Stone from a deb package on Ubuntu/Debian and I will conclude it in 2-3 days.

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am an advanced computer science student with experience in writing technical documentation and installing software on Linux systems. Although I haven't worked directly on Docker projects, I have knowledge of package management and environment configuration on Ubuntu/Debian. I am a member of the DOJO Coding community, where I collaborate on creating technical guides to facilitate the use of various tools. My goal is to ensure that the documentation is clear, accurate, and easy to follow for users.

### How I plan on tackling this issue
To address this issue, I will create a documentation file in docs/pages/install/debian.md with a brief introduction to Stone and its purpose. I will provide detailed instructions for downloading and installing the .deb package on Ubuntu/Debian systems, including using dpkg and resolving missing dependencies with apt-get. I will also include a section for verifying the installation with a version check command and tips for troubleshooting common issues. I am ready to work on this.

**Comment by dmirgaleev** [comment]
Hello @od-hunter! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by od-hunter** [comment]
> Hello @od-hunter! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress! Happy hacking!

Thank you ser🫡

**Comment by dmirgaleev** [comment]
Hey @od-hunter! Do you have any progress so far?

**Comment by od-hunter** [comment]
> Hey @od-hunter! Do you have any progress so far?

On it ser, will push a pr today.

**Comment by dmirgaleev** [comment]
Friendly heads up that you have until Sunday (October 6) to push your final PR. @mexes20
