### ISSUE TITLE
[Book] Stone configuration

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#29]
Add a documentation page that describes how to create a configuration file for the Stone prover, what are the security settings of the FRI protocol, what is the format of the config file.

Path to your markdown file: `docs/pages/usage/configuration.md`

References:
* https://blog.lambdaclass.com/overview-of-the-stone-prover/
* https://www.starknet.io/blog/diving-into-the-code-of-stone-prover-video/

**Comment by Jemiiah** [comment]
Hi @dmirgaleev ,Please let me work on this when od hack starts.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I’m a blockchain developer with strong experience in building smart contracts and working with blockchain protocols. I’ve worked with technologies like Solidity, Cairo, and zero-knowledge proofs, which are at the core of systems like the Stone prover. I also have skills in Backend/Frontend web development using TypeScript, and ReactJS, NestJS, so I can document and explain complex setups in a way that makes sense.

### How I plan on tackling this issue
With my background in zk-proof systems and experience in dApp development, I understand how to configure protocols to ensure security and efficiency. This means I can write documentation that’s not only clear but also practical for developers.

First, I’d do a deep dive into the Stone prover and FRI protocol to fully understand how the configuration file works and what the security settings are. From there, I’ll break down the documentation into three parts:

Creating the Config File – I’ll guide users through setting up the config file, explaining each option in a simple way, with recommended settings.

FRI Protocol Security Settings – I’ll break down the security options for the FRI protocol, like how to set up soundness and error correction, and explain what each setting does in terms of security.

Config File Format – I’ll provide the actual format of the config file (JSON or YAML), with explanations for each field and sample configurations to make things easy to follow.

Finally, I’ll test everything myself to make sure the instructions are correct and work in practice. By keeping it clear and straightforward, I’ll make sure the documentation is helpful for both beginners and experienced developers.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a front-end and also a blockchain developer with experience in technical writing and documentation 

### How I plan on tackling this issue
I can implement a very good documentation on the Stone configuration

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
@dmirgaleev I would love to work on this issue when ODHack starts I have worked on about 6 different documentation issue on different repositories this is my OD Hack portfolio : https://app.onlydust.com/u/Jemiiah I have a very good track record on docs issues here are some of the repositories I have worked on:
Flex-NFT-Marketplace/Flex-Marketplace-Contract#106
dragan2234/worldcoin-scroll-bridge#13
dragan2234/worldcoin-scroll-bridge#11
NethermindEth/StarknetByExample#200

### How I plan on tackling this issue
Step 1: Understand the Purpose
I need to describe three key aspects in the documentation:

1. How to create a configuration file for the Stone prover.
2. The security settings of the FRI protocol.
3. The format of the configuration file.

Step 2: Create a New Markdown File
First, I’ll navigate to the correct path in my project:
`cd docs/pages/usage/`

Next, I’ll create a markdown file named configuration.md:
`touch configuration.md`

Step 3: Structure the Documentation
I’ll open `configuration.md` in my preferred text editor and structure the content using headers for clarity. Here's a basic outline that I’ll follow:

`# Stone Prover Configuration

This page explains how to configure the Stone prover, set up the security settings for the FRI protocol, and the format of the configuration file.

## 1. Creating a Configuration File

To set up a configuration file for the Stone prover, I will follow these steps:
1. Define the proof parameters, such as `max_iterations`, `proof_size`, and `error_rate`.
2. Set up prover-specific options (e.g., `batch_size`, `parallelism_level`).
3. Specify paths for input/output data using `input_file` and `output_file`.

Example:
```json
{
  "max_iterations": 10,
  "proof_size": 512,
  "error_rate": 0.0001,
  "batch_size": 100,
  "parallelism_level": 4,
  "input_file": "/path/to/input",
  "output_file": "/path/to/output"
}`

2. Security Settings of the FRI Protocol
The FRI protocol (Fast Reed-Solomon Interactive Oracle Proof of Proximity) strengthens the security of the prover. I will configure these settings:

Security Level: Define the acceptable security margin, e.g., `128-bit security`.
Sampling Rate: Determine how often random challenges are sampled to ensure proof soundness.
Domain Size: Ensure that the domain size matches the prover's requirements for the security level.

Example settings:

`{
  "fri_security_level": 128,
  "fri_sampling_rate": 0.5,
  "fri_domain_size": 1024
} `

3. Configuration File Format
The Stone prover configuration file is typically in JSON format and follows this structure:

i. max_iterations: Maximum number of proof iterations.
ii. proof_size: Size of the proof in bytes.
iii. error_rate: Permissible error rate in proof generation.
iv. batch_size: Number of operations processed in parallel.
v. parallelism_level: Number of threads/processors to use.
vi. input_file: Path to the input data file.
vii. output_file: Path to the generated proof.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hi, I'm Alvaro Lazarus a passionate blockchain developer with experience on Solidity, Cairo, Rust, TypeScript, Python and zero-knowledge proofs. I love working on clean documentations which makes me confident I can complete this issue perfectly, Id love for this to be my first contribution to the Stone-Packaging project.

### How I plan on tackling this issue
1. Research: Explore the Stone prover and FRI protocol to gain a solid understanding of the configuration file and its security settings.

2. Documentation Structure: Break the documentation into three main parts:

- Config File Creation: Offer a step-by-step guide for setting up the config file, with clear explanations and suggested settings.
- FRI Protocol Security Options: Describe the security features of the FRI protocol, focusing on soundness and error correction.
- File Format: Detail the format of the config file (JSON or YAML), including explanations for each field and examples to illustrate usage.

3. Verification: Test all instructions to confirm they are accurate and functional.

4. Maintain Clarity: Ensure the documentation is easy to follow and accessible for developers of all skill levels.

**Comment by dmirgaleev** [comment]
Hello @Jemiiah! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by Jemiiah** [comment]
thank you @dmirgaleev already in the group if I have any question won't hesitate to ask

**Comment by Jemiiah** [comment]
@dmirgaleev would be creating a PR today sorry for the delay

**Comment by dmirgaleev** [comment]
Friendly heads up that you have until Sunday (October 6) to push your final PR. @Jemiiah

**Comment by Jemiiah** [comment]
okay great sir
