### ISSUE TITLE
[Book] Verifying Stone proof in Ethereum

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#34]
Add a documentation page that provides a step by step guide on how to create and verify proof on Ethereum blockchain. You’ll need to use Stone with the stone-cli tooling available at https://github.com/zksecurity/stone-cli

Path to your markdown file: `docs/pages/advanced/ethereum.md`

References:
* https://github.com/zksecurity/stone-cli?tab=readme-ov-file#how-to-create-proofs-and-verify-them-on-ethereum

**Comment by Kaminar-i** [comment]
hey @dmirgaleev let me work on this please

**Comment by guha-rahul** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a ethereum sc dev with some experience in cryptography who have used the stwo prover before.I think that can be leveraged here.

### How I plan on tackling this issue
1. Go through the stone prover cli and make it work.
2. generate all the artifacts and verify the proof using the Solidity verifier deployed on Ethereum,

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

**Comment by dmirgaleev** [comment]
Hey @guha-rahul! Do you have any progress so far?

**Comment by dmirgaleev** [comment]
Friendly heads up that you have until Sunday (October 6) to push your final PR. @guha-rahul
