### ISSUE TITLE
[Book] Verifying Stone proof on Starknet

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#35]
Add a documentation page describing how to create and verify Stone proof on Starknet. You will be using Integrity verifier available at https://github.com/HerodotusDev/integrity

In addition to verification instructions you’ll also need to provide a guide on how to deploy integrity contracts.

Path to your markdown file: `docs/pages/advanced/starknet.md`

References:
* https://github.com/HerodotusDev/integrity?tab=readme-ov-file#starknet-proof-verification

**Comment by Jemiiah** [comment]
Hi @dmirgaleev ,Please let me work on this when od hack starts.

**Comment by evgongora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hi, I'm Erick part of Dojo Coding, and I'll be working on issue #35 as part of ODHack8.0.

While I don't have direct experience in writing documentation, I have a strong background in blockchain development, particularly with Starknet and smart contract verification. This aligns well with the task, and I’m confident that I can create a clear and comprehensive guide.

### How I plan on tackling this issue
Here’s how I will approach the task:

Review the Integrity Verifier and relevant references to fully understand how to create and verify Stone proofs on Starknet.
Write a step-by-step guide that explains how to deploy integrity contracts and verify proofs on Starknet using the provided verifier.
Ensure clarity and accessibility, making the documentation easy to follow for both new and advanced users.
Place the markdown file in the specified path: docs/pages/advanced/starknet.md.
Self-review for accuracy and completeness before submitting the PR for review.

**Comment by mahesh-dalle** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I have some experience in cryptography. and cairo, and this can be leverged in learning about the stone prover and verifying the proof on starknet

### How I plan on tackling this issue
prepare the call data for proof and use one of the verifier contracts on sepolia to verify the proof

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo



### How I plan on tackling this issue
please kindly assign me and i'll get straight to work

**Comment by evgongora** [comment]
Hello @dmirgaleev! Thank you so much for assigning me the issue, where can I contact you for questions?

**Comment by dmirgaleev** [comment]
Hello @evgongora! Please, don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask any questions and share progress! And happy hacking!

**Comment by dmirgaleev** [comment]
Friendly heads up that you have until Sunday (October 6) to push your final PR @evgongora
