### ISSUE TITLE
[Book] Links

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#36]
Add a documentation page containing useful links to third party resources. Every link has to be accompanied with a brief description. Please, feel free to add more links if you feel they are relevant.

- [Madara Prover API](https://github.com/Moonsong-Labs/madara-prover-api)
- [Stone Prover SDK](https://github.com/Moonsong-Labs/stone-prover-sdk)
- [Stone CLI](https://github.com/zksecurity/stone-cli)
- [STARK EVM Adapter](https://github.com/zksecurity/stark-evm-adapter)
- [Integrity Calldata Generator](https://github.com/HerodotusDev/integrity-calldata-generator)
- https://github.com/cartridge-gg/cairo-proof-parser
- https://zksecurity.github.io/stark-book/

Path to your markdown file: `docs/pages/resources.md`

**Comment by martinvibes** [comment]
hey @dmirgaleev let me work on this please

**Comment by Iwueseiter** [comment]
Hi @dmirgaleev Can I work on this?
Here is a link to a comprehensive docs I've written and have been merged https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/107

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hi  am a frontend developer with some experience writing smart contracts using cairo and solidity. i have experience contributing to documentation and writing technical documentation i believe this will come in handy in this project kindly assign me.


### How I plan on tackling this issue
1. create the markdown file : docs/pages/resources.md

2. After understanding the contents of the links by visiting and reading the documentation in the link
3. giving a well formated markdown 

example:

# Useful Resources

This page contains a collection of third-party resources related to Cairo, Stark-based proving systems, and other relevant tools. Each resource includes a brief description to help you understand its purpose and how it can be useful.

## APIs and SDKs

### [Madara Prover API](https://github.com/path-to-madara-prover-api)
The Madara Prover API provides a set of functionalities to integrate zero-knowledge proof systems into your applications. It offers developers the ability to generate and verify proofs in a streamlined way, with support for various proving methods.

### [Stone Prover SDK](https://github.com/path-to-stone-prover-sdk)
The Stone Prover SDK is a toolkit for integrating the Stone Prover system into your applications. It provides easy-to-use functions for creating, submitting, and verifying Cairo-based proofs using the Stone Prover protocol.

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I'm a frontend and smart contract developer. I've contributed to Projects here on onlydust
 and with that experience, I would handle this task as expected. This would also be my first time
contributing to this project.

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community. I've done documentation contributions in the past.

### How I plan on tackling this issue
I would approach this issue in the following way:
- Read each link to get an idea of the main topic
- Draft a brief description for each link
- Create a draft PR to ask for feedback regarding the brief descriptions
- Modify accordingly given the feedback of the maintainers

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

I have also worked on the Starknet Docs.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
My name is Benjamin, and I've made 18 contributions since joining OnlyDust. As an experienced full-stack JavaScript developer, I have a strong background in writing documentation, which I believe is crucial for any project. I’m excited to enhance the stone packaging project by creating a dedicated resources page that will provide useful links to third-party resources.

### How I plan on tackling this issue
I plan to make a new markdown file at docs/pages/resources.md. This page will be a handy reference for developers and users looking for helpful external resources. Each link will come with a short description to explain what it is and why it’s useful.

Here’s what I want to include:

1. Madara Prover API: A tool for checking proofs made by the Madara Prover, which can help us add verification features to our apps.

2. Stone Prover SDK: This SDK makes it easier to create and check proofs using the Stone Prover, perfect for developers working with zero-knowledge proofs.

3. Stone CLI: A command-line tool to work with the Stone Prover directly, allowing us to generate and verify proofs from the terminal.

4. STARK EVM Adapter: This tool helps connect STARK-based applications with Ethereum, letting us take advantage of STARK benefits while using Ethereum smart contracts.

5. Integrity Calldata Generator: A utility that helps generate integrity calldata, which keeps our data safe and reliable.

6. Cairo Proof Parser:  A library that helps parse Cairo proofs, great for anyone building Cairo-based applications.

7. STARK Book: An educational resource that explains STARKs and how to use them, perfect for anyone wanting to learn more about zero-knowledge proofs.

I’m also open to adding more links if I find other resources that could help our community. Once I have everything together, I’ll format the markdown file to make it easy to read and navigate.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
i am a blockchain developer and i am avaliable to work .kindly assign

### How I plan on tackling this issue
To approach this issue:
1. Create the Markdown File: Start with `docs/pages/resources.md`.
2.*List Resources: Include the links 
3. Format the Content: Use headers and lists for clarity.
4.Review and Save: Ensure accuracy, then save the file.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
i will Identify Relevant Resources
Research and gather links to relevant third-party resources:
Official documentation for integrated libraries and frameworks
Tutorials and guides for specific technologies
Community forums and discussion groups
Blogs and articles from industry experts
Categorize Resources
Organize links into categories:
Development
Integration
Troubleshooting
Security
Best Practices

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue
please kindly assign me and i'll get straight to work

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello @dmirgaleev

I'm a software engineer from Costa Rica and a member of Dojo Coding. I have worked with technologies such as JavaScript, Node.js, PhP, Java, C#, Cairo. I'd love the opportunity to help with this issue and contribute to your project.

### How I plan on tackling this issue
For this issue I will:

`1.` Understand the Content: I will visit each provided link, review the documentation, and gain a solid understanding of its content.

`2.` Organize Information: After reviewing the links, I will organize the content into a well-formatted Markdown file. The content will include headings, descriptions, and appropriate references to the documentation.

`3.` Create the Markdown File: I will ensure the Markdown file is properly formatted with clean sections, bullet points, and relevant links, making it easy to navigate and understand.

Looking forward to your feedback!

Best regards,

Diego Duarte Fernández.

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.


### How I plan on tackling this issue
To address the problem, I would access docs/pages/resources.md and add the links with brief descriptions:

Madara Prover API: Interface for Madara proof system.
Stone Prover SDK: SDK to integrate Stone Prover.
Stone CLI: CLI to manage Stone proofs.
STARK EVM Adapter: Connects STARKs with EVM.
Integrity Calldata Generator: Generates calldata to ensure transaction integrity.
I would also include the provided additional links, then review to ensure everything works correctly.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hi, I'm Alvaro Lazarus a passionate blockchain developer with a good amount of experience on this ecosystem, I love working on clean documentations which makes me confident I can complete this issue, I haven't worked with Stone Packaging before but would love to contribute to the project.

### How I plan on tackling this issue
Id add and read through the links so I can write a concise, user friendly description for each one while providing enough useful information. And lastly I would look into the project a bit deeper to see if there's any other useful links I could add.

Best regards,
Lazarus

**Comment by diegoTech14** [comment]
Thanks!! I will start ASAP
