### ISSUE TITLE
Webhook based trigger

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#6]
For every workflow instead of 
```
on:
  push:
    branches:
      - 'master'
```

Should be used 
```
on:
  repository_dispatch:
```
based on commits to the main branch of https://github.com/baking-bad/stone-prover.

- Testing should be done in a forked repo and testing results should be provided.
- Pull requests with workflows should be created both for https://github.com/baking-bad/stone-prover and current repo.

**Comment by CollinsC1O** [comment]
Hi @dmirgaleev I'm a frontend developer and also a blockchain developer and i will love to work on this. I'm very ready to work

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
By updating the workflow file to use repository dispatch.

**Comment by dmirgaleev** [comment]
Hello @JoE11-y! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by dmirgaleev** [comment]
Hey @JoE11-y! Do you have any progress so far?

**Comment by JoE11-y** [comment]
Will you give an update in 2hrs.
Thanks @dmirgaleev

**Comment by dmirgaleev** [comment]
Thank you for your great job!
